repositories:
  - name: chartcenter
    url: https://repo.chartcenter.io

releases:

#  LoadBalancer
#  * MetalLB as Load Balancer
#  * On some installers like Kubespray this is included

- name: metallb-config
  chart: chartcenter/incubator/raw
  namespace: metallb-system
  createNamespace: true
  wait: true
  version: "0.2.5"
  values:
    - environments/{{ .Environment.Name }}/metallb/resources.yaml
    - environments/all/metallb/templates.yaml.gotmpl
  labels:
    tier: loadbalancer
    scope: metalconfig

- name: metallb-system
  namespace: metallb-system
  createNamespace: true
  wait: true
  chart: ./metallb
  hooks:
    - events:
        - prepare
        - cleanup
      command: "./helmify.sh"
      args: ["{{`{{if eq .Event.Name \"prepare\"}}build{{else}}clean{{end}}`}}", "{{`{{.Release.Chart}}`}}", "{{`{{.Environment.Name}}`}}"]
  labels:
    tier: loadbalancer
    scope: metalsystem

#  AUTO LABEL NODES for usb/pci devices
#  * node-feature-discovery

- name: node-feature-discovery
  namespace: nf-discovery
  createNamespace: true
  wait: false
  chart: chartcenter/k8s-at-home/node-feature-discovery
  version: '{{ .Values | get "node_feature_discovery" "2.0.0" }}'
  values:
    - environments/{{ .Environment.Name }}/nf-discovery/values.yaml
  labels:
    tier: discovery
    scope: node-feature

environments:
  dev:
    secrets:
      - environments/dev/secrets.yaml
  nuc:
    secrets:
      - environments/nuc/secrets.yaml
