prometheus-blackbox-exporter:
  serviceMonitor:
    enabled: true
    defaults:
      labels:
        release: monitoring
  config:
    modules:
      http_2xx:
        prober: http
        timeout: 5s
        http:
          valid_http_versions: ["HTTP/1.1", "HTTP/2"]
          no_follow_redirects: false
          preferred_ip_protocol: "ip4"
      ssh_banner:
        prober: tcp
        timeout: 5s
        tcp:
          query_response:
          - expect: "^SSH-2.0-"
      ts_banner:
        prober: tcp
        timeout: 5s
        tcp:
          query_response:
          - expect: "^TS3"
