descheduler:
  cmdOptions:
    evict-local-storage-pods: '' 
  nameOverride: "descheduler"
  schedule: "*/2 * * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  deschedulerPolicy:
    strategies:
      "RemoveDuplicates":
        enabled: false

      # zigbee2mqtt nodeAffinity
      "RemovePodsViolatingNodeAffinity" :
        enabled: true
        params:
          nodeAffinityType:
          - requiredDuringSchedulingIgnoredDuringExecution
          namespaces:
            include: iot
          labelSelector:
            matchLabels:
              app.kubernetes.io/name: zigbee2mqtt
      "RemovePodsHavingTooManyRestarts":
        enabled: true
        params:
          podsHavingTooManyRestarts:
            podRestartThreshold: 100
            includingInitContainers: true
          namespaces:
            include: iot
          labelSelector:
            matchLabels:
              app.kubernetes.io/name: zigbee2mqtt

      "RemovePodsViolatingInterPodAntiAffinity":
        enabled: false
      "LowNodeUtilization":
        enabled: false
