---
- name: Set hostname
  hostname:
    name: "{{ ansible_hostname }}"

- name: Set hosts
  template:
    src: hosts.j2
    dest: /etc/hosts
    mode: 0644

- name: Install netplan
  apt:
    name: netplan.io
    state: present

- name: Configure network interface
  template:
    src: netplan.j2
    dest: "/etc/netplan/01-netcfg.yaml"
    mode: 0644
  notify:
    - apply network interface
    - restart server

- name: Enable systemd-networkd instead of NetworkManager
  systemd:
    name: systemd-networkd
    enabled: true
    masked: false
  notify: restart server

- name: Disable NetworkManager
  systemd:
    name: NetworkManager
    enabled: false
    masked: true
  ignore_errors: true
  notify: restart server

- name: Enable IPv6
  sysctl:
    name: "{{ item }}"
    value: '0'
    sysctl_file: /etc/sysctl.d/20-ipv6.conf
    sysctl_set: true
  loop:
    - net.ipv6.conf.all.disable_ipv6
    - net.ipv6.conf.default.disable_ipv6

- meta: flush_handlers

- name: Remove NetworkManager (allow disable ipv6)
  apt:
    name: network-manager
    state: absent
