---

- hosts: all
  any_errors_fatal: true
  become: true
  roles:
    - geerlingguy.ntp
    - prereq
    - download-k3s

- import_playbook: ../../playbooks/install/k3s-nodes.yml

- import_playbook:  ../../playbooks/install/manage-k8s-dependencies.yml

- import_playbook:  ../../playbooks/install/storage.yml
  when: (install_ceph is defined) and (install_ceph)

#- import_playbook: ./monitoring/monitoring-etcd-kubespray.yml

