apiVersion: v2
name: nf-discovery
description: "Node Feature Discovery"
type: application
version: 0.1.0
appVersion: "1.0"

dependencies:
- name: node-feature-discovery
  repository: https://k8s-at-home.com/charts/
  version: 2.0.0
