node-feature-discovery:
  sources:
    - cpu
    # - custom
    # - iommu
    # - kernel
    # - local
    # - memory
    # - network
    # - pci
    - storage
    # - system
    - usb

  config: |
    sources:
      usb:
        deviceClassWhitelist:
          - "02"
          - "0e"
          - "ef"
          - "fe"
          - "ff"
        deviceLabelFields:
          - "class"
          - "vendor"
          - "device"
  master:
    replicaCount: 1
    tolerations:
      - key: "node-role.kubernetes.io/master"
        operator: "Equal"
        value: ""
        effect: "NoSchedule"
    resources:
      requests:
        cpu: 25m
        memory: 22Mi
      limits:
        cpu: 25m
        memory: 22Mi
  worker:
    resources:
      requests:
        cpu: 25m
        memory: 18Mi
      limits:
        cpu: 25m
        memory: 18Mi
