apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: blackbox-exporter
  namespace: argocd
spec:
  destination:
    namespace: monitoring
    server: 'https://kubernetes.default.svc'
  source:
    path: ''
    repoURL: 'https://prometheus-community.github.io/helm-charts'
    targetRevision: 4.10.2
    chart: prometheus-blackbox-exporter
    helm:
      valueFiles:
        - values.yaml
  project: infra
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

