spec:
  source:
    repoURL: https://github.com/sdelrio/k8s-gitops.git
    targetRevision: feature/gitopstest
  destination:
    server: https://kubernetes.default.svc
  helm:
    valueFiles:
      - values-nuc.yaml

apps:
  - name: apps-nuc
    namespace: argocd
    path: apps-nuc
    sync: true
  - name: nf-discovery
    namespace: nf-discovery
    project: iot
    helm:
      enabled: true
    sync: true


