{{- $top := . }}
{{- range .Values.apps }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .name }}
  namespace: argocd
spec:
  project: {{ .project | default "default" }}
  source:
    repoURL: {{ .repoURL | default $top.Values.spec.source.repoURL }}
    {{- if .helm }}
    helm:
      valueFiles:
        - values.yaml
    {{- end}}
    targetRevision: {{ .targetRevision | default $top.Values.spec.source.targetRevision }}
    path: {{ .path | default (print "deployments/" .name) }}
  destination:
    server: {{ .server | default $top.Values.spec.destination.server }}
    namespace: {{ .namespace }}
  {{- if .sync }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  {{- end }}
{{- end }}
