defaultSettings:
# Default Data Path, default /var/lib/longhorn/
  defaultDataPath: /var/lib/longhorn
# Example: s3://backupbucket@us-east-1/backupstore
#  backupTarget: ~
# Example: s3-secret
#  backupTargetCredentialSecret: ~
#  replicaSoftAntiAffinity: false
#  storageOverProvisioningPercentage: 200
#  storageMinimalAvailablePercentage: 25
#  upgradeChecker: true
# The default number of replicas when creating the volume from Longhorn UI.
# For Kubernetes, update the numberOfReplicas in the StorageClass
#  defaultReplicaCount: 3
#  guaranteedEngineCPU: 0.25
#  priorityClass: high-priority
