apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: iot
  namespace: argocd
spec:
  description: Internet Of Things Deployments
  destinations:
  - namespace: 'iot'
    server: https://kubernetes.default.svc
  - namespace: 'argocd'
    server: https://kubernetes.default.svc
  clusterResourceWhitelist:
  - group: rbac.authorization.k8s.io
    kind: ClusterRole
  - group: rbac.authorization.k8s.io
    kind: ClusterRoleBinding
  - group: policy
    kind: PodSecurityPolicy
  sourceRepos:
  - https://github.com/sdelrio/k8s-gitops.git
  - https://k8s-at-home.com/charts
  - https://kubernetes-sigs.github.io/descheduler

#Resource policy:PodSecurityPolicy is not permitted in project iot.
