apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: blackbox-exporter
  namespace: argocd
spec:
  project: infra
  source:
    repoURL: https://github.com/sdelrio/k8s-gitops.git
    targetRevision: feature/gitopstest
    path: deployments/blackbox-exporter
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
