#resources:
#- https://raw.githubusercontent.com/metallb/metallb/v0.9.4/manifests/namespace.yaml
#- https://raw.githubusercontent.com/metallb/metallb/v0.9.4/manifests/metallb.yaml
# On first install only
#- kubectl create secret generic -n metallb-system memberlist --from-literal=secretkey="$(openssl rand -base64 128)"
