repositories:
  - name: k8s-at-home
    url: https://k8s-at-home.com/charts/

releases:

#  Zigbee-to-MQTT
#  https://www.zigbee2mqtt.io/

- name: zigbee2mqtt
  chart: k8s-at-home/zigbee2mqtt
  version: '{{ .Values | get "zigbee2mqtt_version" "6.0.0" }}'
  values:
    - environments/{{ .Environment.Name }}/values.yaml.gotmpl
  labels:
    tier: home
    scope: zigbee2mqtt

environments:
  dev:
    secrets:
      - ../../secrets/dev/secrets.yaml
    values:
      - zigbee2mqtt_version: '6.2.1'
  nuc:
    secrets:
      - ../../secrets/nuc/secrets.yaml
