repositories:
  - name: chartcenter
    url: https://repo.chartcenter.io

releases:

- name: postgresql
  chart: chartcenter/bitnami/postgresql
  version: '{{ .Values | get "concourse_version" "10.1.4" }}'
  namespace: devops
  createNamespace: true
  values:
    - environments/{{ .Environment.Name }}/postgresql/values.yaml.gotmpl
  labels:
    tier: devops
    scope: postgresql

- name: concourse
  chart: chartcenter/concourse/concourse
  version: '{{ .Values | get "concourse_version" "14.5.2" }}'
  namespace: devops
  createNamespace: true
  needs:
    - devops/postgresql
  values:
    - environments/{{ .Environment.Name }}/concourse/values.yaml.gotmpl
  labels:
    tier: devops
    scope: concourse

environments:
  dev:
    secrets:
      - ../deployments-1/environments/dev/secrets.yaml
      - ../deployments-2/environments/dev/secrets.yaml
  nuc:
    secrets:
      - ../deployments-1/environments/nuc/secrets.yaml
      - ../deployments-2/environments/nuc/secrets.yaml
