---
- name: install rook-ceph operator
  community.kubernetes.helm:
    chart_repo_url: https://charts.rook.io/release
    chart_ref: rook-ceph
    chart_version: v1.4.7
    name: rook-ceph
    namespace: rook-ceph
    create_namespace: yes
    wait: yes
    values: "{{ lookup('template', 'operator.yml.j2') | from_yaml }}"

